### ISSUE TITLE
Initialization problem

### ISSUE THREAD

**Issue by fsch0203** [nbabanov/cordova-chromecast#4]
Hi Nikolay,

Thanks for this plugin, it is just what I need for radio app I am working on. But up to now I don't get it working. The build process doen't give any errors, but using your example code I can't get it initialized. When I call initializeCastApi() I get the error: 'Cannot read property 'SessionRequest' of undefined'. So it seems that the object chrome.cast is not defined. It's probably a simple mistake I make, but I can't figure it out.

Thanks, 
Frans Schrijver

**Comment by nbabanov** [comment]
Hello Frans,

Have you tried using the `deviceready` event? :)

**Comment by fsch0203** [comment]
Indeed! That seemed to be the problem. Thanks for the help!
Frans
